language: erlang
env:
    # Enable python 2 and python 3 builds. Python3 available in Ubuntu 12.04.
    - PYTHON=python PYSUF=''
    - PYTHON=python3 PYSUF=3
# command to install dependencies
install:
    - sudo apt-get install $PYTHON-dev
    - sudo apt-get install $PYTHON-numpy
    - sudo apt-get install $PYTHON-scipy
    - sudo apt-get install $PYTHON-setuptools
    - sudo apt-get install $PYTHON-nose
    - $PYTHON setup.py build
    - sudo $PYTHON setup.py install
# command to run tests
script:
    - mkdir for_test
    - cd for_test
    - $PYTHON -c "import variational_sampler as vs; vs.test(); print(vs.__file__)"